
# properties usadas por la app en su logica interna
cl.mineduc.debug.ips=10.100.17.15

# SERVER
server.port=9310
server.servlet.contextPath=/api-sidep-asistencia

#DATASOURCE
api.sidep.datasource.driver-class-name=org.postgresql.Driver
api.sidep.datasource.url=jdbc:postgresql://192.168.32.40:5432/sidep
api.sidep.datasource.username=adm_sidep_prod
api.sidep.datasource.password=adm_sidep_prod

# LOGGING
#logging.level.root = DEBUG
#logging.level.cl.mineduc.api_sidep_sostenedor = DEBUG
#logging.level.com.zaxxer.hikari = DEBUG
#logging.level.com.ibatis.common = DEBUG
#logging.level.java.sql = DEBUG
